### ISSUE TITLE
"There is no formatter for 'gradle' files installed."

### ISSUE THREAD

**Issue by NatoBoram** [nvuillam/vscode-groovy-lint#90]
Hi! I'm trying to format a gradle file, but I got this error.

> There is no formatter for 'gradle' files installed.

![image](https://user-images.githubusercontent.com/10495562/97380640-db1d6180-189d-11eb-9e77-67bc633ea693.png)

```yaml
Version: 1.51.0-insider
Commit: e5c0007ce0e9a3816679cba674d03376c03726e3
Date: 2020-10-27T05:37:14.199Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
